// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SSC_BoxingMayhem",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "SSC_BoxingMayhem",
            targets: ["AppModule"],
            bundleIdentifier: "Nakama.SSC-BoxingMayhem",
            teamIdentifier: "49V8Q5W76J",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeLeft
            ],
            capabilities: [
                .camera(purposeString: "Would you like to allow access to play this game using your camera")
            ],
            appCategory: .actionGames
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("MLModels"),
                .copy("Sounds")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
